main:main.c
	gcc -o main main.c include/alutInputStream.c include/alutUtil.c include/alutError.c -Iinclude -Llib -lalut -lopenal -Wl,-rpath,lib -DHAVE_STDINT_H -DHAVE_UNISTD_H -DHAVE_STAT -DHAVE_USLEEP
