pain:main.c
	gcc -o main main.c include/alutInputStream.c  include/alutUtil.c include/alutError.c alhelpers.c -Iinclude -Llib -lalut -lopenal  -Wl,-rpath,lib -lavcodec -lavfilter -lavutil -lswscale -lavdevice -lavformat -lswresample -lavresample   -DHAVE_STDINT_H -DHAVE_UNISTD_H -DHAVE_STAT -DHAVE_USLEEP
